### PR TITLE
Deployment preparation: gauge adder v3 migrator

### PR DESCRIPTION
**Pull request by EndymionJkb**
# Description

Perform the migration from Gauge Adder v2 to v3. (Fork test is not yet finalized.)

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [X] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes
- [X] Complex code has been commented, including external interfaces
- [ ] Tests are included for all code paths
- [X] The base branch is either `master`, or there's a description of how to merge

### CODE REVIEW

**Comment by TomAFrench** [comment]
I get the same build-info as committed when building d6bf6d3

**Comment by TomAFrench** [comment]
@EndymionJkb can you give this a final once over and if it looks good to you then I can deploy.

**Review by EndymionJkb — COMMENTED** [review]
Thanks, Tom! The factory tests you edited are what I wasn't sure about. Looks good to go now. (It won't let me approve my own PR.)

**Comment by TomAFrench** [comment]
No worries, I'll approve and merge once CI runs

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
