### PR TITLE
Update dependencies

### LINKED ISSUE #1957: Review / Upgrade dependencies
From the ToB audit, our dependencies are out of date. In particular, the Node version might be different locally vs on CI.

### PR DESCRIPTION
**Pull request by jubeira**
# Description

This PR bumps the npm dependencies as suggested by `yarn`.

As a first approach, these were the steps:
- Run `yarn up`
- Try build, fix errors
- Try running tests, fix errors
  - The new Mocha version sometimes throws a different error message when reverting, so the code that parses balancer errors had to be adjusted.
  - `balancer-js` importing a json broke, so that part was changed to reading it using `fs`.
- Adjusted dependencies in `deployments`, since the major bump in `chalk` and `node-fetch` broke some imports. The suggestion here is to stick within the same major version.

*Linter update pending*; it will be done in future PRs.

### Major changes

These libraries had major upgrades; linters excluded:

- `rollup`: ^2.52.8 --> ^3.2.3
  - `plugin-commonjs`: ^19.0.0 --> ^23.0.2
  - `plugin-node-resolve`: ^13.0.0 --> ^15.0.1
  - `plugin-typescript`: ^8.2.1 --> ^9.0.2
  - `plugin-dts`: ^3.0.2 --> ^5.0.0
- `mocha`: ^8.0.3 --> ^10.1.0
- `types/mocha`: ^8.0.3 --> ^10.0.0 
- `ts-node`: ^8.10.2 --> ^10.9.1

The remaining changes are minor / patch upgrades which shouldn't cause trouble.

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [x] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [x] The diff is legible and has no extraneous changes
- [ ] Complex code has been commented, including external interfaces --> N/A
- [ ] Tests are included for all code paths --> N/A
- [x] The base branch is either `master`, or there's a description of how to merge

## Issue Resolution

Closes #1957

### CODE REVIEW

**Comment by jubeira** [comment]
I've double checked breaking changes for the major updates and we should be OK (the tests are also passing).

> About the linters:
> 
> Updated Typescript linters suggest some changes, but the impact is rather limited. I think we can proceed with those.
> Updated Solidity linters suggest a lot of changes. I'd either stick with the current ones, or perform the updates separately.

Input about this is welcome. tl;dr; I haven't applied the suggested changes yet; my suggestion is to apply changes to TS files, and stay with the old solidity linters for now.

**Comment by jubeira** [comment]
Update: as discussed offline, we'll defer linter updates for a future PR.

**Comment by TomAFrench** [comment]
If I delete `node_modules` and any build files then run `yarn build` I get the error below:

```
➤ YN0000: [@balancer-labs/balancer-js]: internal/modules/cjs/loader.js:905
➤ YN0000: [@balancer-labs/balancer-js]:   throw err;
➤ YN0000: [@balancer-labs/balancer-js]:   ^
➤ YN0000: [@balancer-labs/balancer-js]: 
➤ YN0000: [@balancer-labs/balancer-js]: Error: Cannot find module 'node:process'
➤ YN0000: [@balancer-labs/balancer-js]: Require stack:
➤ YN0000: [@balancer-labs/balancer-js]: - /home/tom/Programming/balancer-core-v2/node_modules/rollup/dist/bin/rollup
➤ YN0000: [@balancer-labs/balancer-js]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
➤ YN0000: [@balancer-labs/balancer-js]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
➤ YN0000: [@balancer-labs/balancer-js]:     at Module.require (internal/modules/cjs/loader.js:974:19)
➤ YN0000: [@balancer-labs/balancer-js]:     at require (internal/modules/cjs/helpers.js:92:18)
➤ YN0000: [@balancer-labs/balancer-js]:     at Module.<anonymous> (/home/tom/Programming/balancer-core-v2/node_modules/rollup/dist/bin/rollup:16:19)
➤ YN0000: [@balancer-labs/balancer-js]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
➤ YN0000: [@balancer-labs/balancer-js]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
➤ YN0000: [@balancer-labs/balancer-js]:     at Module.load (internal/modules/cjs/loader.js:950:32)
➤ YN0000: [@balancer-labs/balancer-js]:     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
➤ YN0000: [@balancer-labs/balancer-js]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
➤ YN0000: [@balancer-labs/balancer-js]:   code: 'MODULE_NOT_FOUND',
➤ YN0000: [@balancer-labs/balancer-js]:   requireStack: [
➤ YN0000: [@balancer-labs/balancer-js]:     '/home/tom/Programming/balancer-core-v2/node_modules/rollup/dist/bin/rollup'
➤ YN0000: [@balancer-labs/balancer-js]:   ]
➤ YN0000: [@balancer-labs/balancer-js]: }
```

**Comment by jubeira** [comment]
> If I delete node_modules and any build files then run yarn build I get the error below:

Readme updated; `rollup:3.x` needs Node ^14.18.0.

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
