### PR TITLE
Make AumProtocolFeeCache aware of Recovery mode

### PR DESCRIPTION
**Pull request by EndymionJkb**

### CODE REVIEW

**Comment by nventuro** [comment]
This feels a bit premature, no? I'm not sure we have a clear understanding of how recovery mode would affect managed pools. Would we really turn off the AUM fee? That feels like a bit of an outreach.

**Comment by EndymionJkb** [comment]
> This feels a bit premature, no? I'm not sure we have a clear understanding of how recovery mode would affect managed pools. Would we really turn off the AUM fee? That feels like a bit of an outreach.

It's the AUM *protocol* fee, not the AUM management fee. If you think it's premature, we could label it with "needs discussion" or something like that. (I could make it a draft.)

**Comment by nventuro** [comment]
Sure, but the reason why we turn off protocol fees in recovery mode is a bit indirect. Let's tag this for later discussion.

**Comment by EndymionJkb** [comment]
Superceded by #1539

**Pull request closed without merging**
