### PR TITLE
[Deployments] Adding Balancer Queries task.

### PR DESCRIPTION
**Pull request by jubeira**
- Task, input, build info, artifacts, readme.
- Output / deployment pending.

### CODE REVIEW

**Comment by nventuro** [comment]
I've checked that the build info at fdb233a6c30966fe2dab65a9175a779922c11d16 matches the artifact in the task.

**Comment by nventuro** [comment]
(sorry!)

**Comment by jubeira** [comment]
Deployed to Arbitrum, Goerli, Mainnet, Optimism and Polygon.

Verification in Optimism is pending; I can't access the dashboard to get the API key. I'll try again later.

**Review by nventuro — APPROVED** [review]
Looks fantastic, congrats on your first deployment! :tada: 

>Verification in Optimism is pending

I just run the verification myself so we don't forget about this, don't worry.

**Pull request merged**
