### PR TITLE
Simplify ValueCompression condition

### PR DESCRIPTION
**Pull request by EndymionJkb**
When writing docs on Foundry tests, found a slight simplfiication.

### CODE REVIEW

**Comment by TomAFrench** [comment]
This is written to match this condition in `ValueCompression`

https://github.com/balancer-labs/balancer-v2-monorepo/blob/3d4594cc2679deed7e7e8da24ee26894a9d889b7/pkg/pool-weighted/contracts/lib/ValueCompression.sol#L58

I think the benefit of matching the require statements in the real code (so we know that we're testing all potential inputs) is worth the extra verbosity.

**Comment by nventuro** [comment]
@TomAFrench I think @EndymionJkb's point is that `bitLength` is a `uint8` in `WordCodec`, so there's no need to check for `<= 255`. We could also make it be a `uint8` in `ValueCompression`.

**Comment by EndymionJkb** [comment]
> @TomAFrench I think @EndymionJkb's point is that `bitLength` is a `uint8` in `WordCodec`, so there's no need to check for `<= 255`. We could also make it be a `uint8` in `ValueCompression`.

Yes; I was writing a Notion doc about the option of using typed uints for input restriction in Foundry (so that it does it for you, and you don't need either assume or bound), using this as an example.

**Comment by TomAFrench** [comment]
> I think @EndymionJkb's point is that bitLength is a uint8 in WordCodec, so there's no need to check for <= 255. We could also make it be a uint8 in ValueCompression.

I'm not entirely sure what you mean here. `WordCodec` takes a uint256 and enforces validity through require statements (one of which being equivalent to restricting values to a uint8). Are you suggesting we change the libraries or the tests?

My point is that fuzzing tests should optimise for being clear about what the range of inputs are and why. Having the condition as it is makes it clear that we're matching that particular require statement to give meaning on why we're adding that `vm.assume`

**Comment by EndymionJkb** [comment]
> I'm not entirely sure what you mean here. `WordCodec` takes a uint256 and enforces validity through require statements (one of which being equivalent to restricting values to a uint8). Are you suggesting we change the libraries or the tests?
> 
> My point is that fuzzing tests should optimise for being clear about what the range of inputs are and why. Having the condition as it is makes it clear that we're matching that particular require statement to give meaning on why we're adding that `vm.assume`

We've generally always used uint256 for libraries; I'd say don't change anything there. To retain consistency, maybe make it uint256 in the test as well, and `bound(bitLength, 2, 255)` ?

**Comment by nventuro** [comment]
Ah I'm sorry, I misread - thought the test was the code. Agree with Tom then - the extra verbosity in the test does no damage at all, and makes it clear we're imposing the exact same condition.

**Pull request closed without merging**
