### PR TITLE
Remove base recovery mode implementation

### PR DESCRIPTION
**Pull request by TomAFrench**
This saves almost 200 bytes from ManagedPool (and is a good practice anyway)

I haven't run tests on all the other contracts this touches so will likely do touch ups to this PR.

### CODE REVIEW

**Review by nventuro — APPROVED** [review]
Lovely

**Comment by TomAFrench** [comment]
Please don't merge unless you like red crosses

**Comment by TomAFrench** [comment]
@nventuro Do you want to have a quick check over this again as there have been a fair number of changes.

**Review by nventuro — APPROVED** [review]
We'll need to add tests to ManagedPool, ComposableStablePool, BaseWeightedPool and LinearPool, since those now have custom recovery mode exits.

**Pull request merged**
