### PR TITLE
Make MockMortalFactory inherit from a proper factory.

### PR DESCRIPTION
**Pull request by TomAFrench**
I wanted to do a dryrun of integrating `MortalFactory` into a real factory contract so changed `MockMortalFactory` to inherit from `MockPoolFactory`.

We've got some annoying inheritance issues but I don't think there's a way round without while keeping `MortalFactory` as a mixin. Let me know what you think.

### CODE REVIEW

**Comment by EndymionJkb** [comment]
I did find the code I had for using this with a real factory. I guess this is fine for testing; do we need it? Maybe just add some documentation? (I'll do that anyway.)

I just changed three lines (inherit from MortalFactory, call the base constructor, and add the check in create), added all the MortalFactory tests, and everything worked:

contract ManagedPoolFactory is MortalFactory {
    constructor(address baseFactory) MortalFactory ((BaseManagedPoolFactory(baseFactory).getVault())) {
        baseManagedPoolFactory = baseFactory;
    }

    function create(...) {
        _ensureEnabled();
        ....
   }
}

**Comment by TomAFrench** [comment]
I'm not sure I follow that code snippet you shared there. Are you expecting the MortalFactory and the base factory to be separate contracts, i.e. MortalFactory is just a proxy calling into the real factory?

**Comment by EndymionJkb** [comment]
> I'm not sure I follow that code snippet you shared there. Are you expecting the MortalFactory and the base factory to be separate contracts, i.e. MortalFactory is just a proxy calling into the real factory?

We're talking past each other somehow. MortalFactory is a Mixin you inherit from to make your factory killable. Maybe ManagedPoolFactory isn't the best example:

```
contract SomeFactory is BasePoolFactory, FactoryWidePauseWindow, MortalFactory {
    constructor(IVault vault) BasePoolFactory(vault) MortalFactory(vault) {
       ...
    }

    function create(...) external returns (address) {
        _ensureEnabled();
        ...
    } 
}

```

**Comment by EndymionJkb** [comment]
Superseded by #1350

**Pull request closed without merging**
